### ISSUE TITLE
Clarify engine instructions

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flaux#43]
I know everything in here is ongoing and changing, but FYI the following directions make it very easy to do a couple incorrect things.

Current directions:
```
Flutter engine uses gclient to manage dependencies.

If you've already cloned the flutter repository:

 1. Copy one of the engine/scripts/*.gclient to the root folder
 2. run gclient sync
 
If you haven't cloned the repository; you could copy the sample gclient file to an empty directory and use gclient sync.
```

Suggested directions:
```
Flutter engine uses gclient to manage dependencies.

If you've already cloned the flutter repository:

 1. Create or choose a new directory on your system to hold the engine code (called the "root folder").
 2. Copy one of the engine/scripts/*.gclient to the root folder
 3. Rename the copied glient script to `.gclient`.
 4. Run gclient sync.

If you haven't cloned the repository; you could copy the sample gclient file to an empty directory and use gclient sync.
```

**Comment by matthew-carroll** [comment]
Maybe our issue was coincidental and the original instructions really meant what they said.

We tried running `gclient sync` from within our `flaux` directory and had some kind of error. We tried in a different directory and it worked. But if the intention is to run `gclient sync` in-place within flaux, then the original instructions make sense for that line.

**Comment by jtmcdole** [comment]
Flaux is in flux right now as we try to get CI up and running (the hardest part of merging). I think my instructions above are from the older experiment; it should be:

- clone the repo
- copy engine/scripts/standard.gclient to the root of flaux
- then run gclient sync

With the old engine repository, you have to gclient `fetch flutter` which will checkout buildroot and fetch the engine.

**Comment by jtmcdole** [comment]
If this is still a problem; re-file on the flutter/flutter repo. Thanks!
